npm install @serialport/parser-inter-byte-timeout@1.1.0
npm install @serialport/bindings@2.0.8
npm install @serialport/bindings-cpp@10.8.0
npm install @serialport/list@8.0.6
npm install @serialport/parser-byte-length@8.0.6
npm install @serialport/parser-cctalk@2.0.2
npm install @serialport/parser-inter-byte-timeout@1.1.0
npm install @serialport/parser-packet-length@10.5.0
npm install @serialport/parser-ready@2.0.2
npm install @serialport/parser-regex@2.0.2
npm install @serialport/parser-slip-encoder@10.5.0
npm install @serialport/parser-spacepacket@10.5.0
npm install @serialport/stream@2.0.5
npm install buffer-alloc@1.2.0
npm install commander@2.20.3
npm install promirepl@1.0.1
npm install prompt-list@3.2.0
npm install to-buffer@1.1.1
npm install xtend@4.0.2
npm install bluetooth-hci-socket@npm:@abandonware/bluetooth-hci-socket@0.5.3-10
npm install bleno@npm:@abandonware/bleno@0.5.1-4
npm install config-yml@0.10.3
npm install ejs@3.1.8
npm install express@4.18.2
npm install nodemon@2.0.21
npm install q@1.5.1
npm install serialport@8.0.6
npm install socket.io@4.6.1
npm install onoff@6.0.3
npm install
